### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/pumpkin-harvest#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by rwnfoo** [comment]
# Header 1
## Header 2 

- bullet1

- [  ]  checkbox

**Comment by yeikel** [comment]
Hello `World`

**Comment by rbryce90** [comment]
# Hello Everyone!

**Comment by smackfu** [comment]
[ ] Done

**Comment by austinsasko** [comment]
`Hello!`

**Comment by PixnBits** [comment]
¡Hola! :octocat:

**Comment by rohanagrawal-amex** [comment]
# Github Training

**Comment by ndanturi** [comment]
Hello 👍

**Comment by Matthew-Mallimo** [comment]
Hello World 🌎

**Comment by djcarpe** [comment]
<details open>
<summary>DJ here...</summary>
<br>
:octocat: 
</details>

**Comment by Sachit31** [comment]
Hello everyone.
